# Generated by Django 4.0.3 on 2022-03-24 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uniflagsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flag',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='flag',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flag',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
